# Generated by Django 2.2.6 on 2019-11-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191005_0359'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='produto.Produto'),
        ),
    ]
